language: c

addons:
  apt:
    packages:
    - libpcap-dev
    - libssl-dev

sudo: required

script:
  - make
  - "[ -e output/libfactory.a ] && make unit_tests"
  - "[ -e output/al_entity ] && make ale_tests"
